on: push
name: Build and Publish
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build Project
      run: |
        npm install
        npm run build --if-present
        
    - name: List output files
      run: ls
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftpx.forpsi.com/www
        ftp-username: adam_bartacom
        ftp-password: paqMsJ7bs
        git-ftp-args: --insecure
        local-dir: dist # This folder is NOT going to upload by default unless you add it to .git-ftp-include
